baseURL = "http://tabboud.github.io/"
languageCode = "en-us"
title = "Tony Abboud"
theme = "book"

[params]
  description = "Engineer + Tinkerer"
  mainIcon = ""
  githubName = "tabboud"
  linkedinName = "tabboud"
  youtubeName = "tdabboud"
  email = "tony.abboud54@gmail.com"

  BookMenuBundle = "/menu"
